import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href="/login">Login</Link>
        <Link href="/register">Register</Link>
      </main>

      <footer></footer>
    </div>
  );
}
